[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
    "opencv-python",
    "pysdl2",
    "pysdl2-dll",
    "open3d",
    "librosa",
    {git = "https://github.com/julianfl0w/vulkan"},
    {git = "https://github.com/julianfl0w/sinode"},
    "screeninfo"
]
build-backend = "setuptools.build_meta"
